In [5]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
from PIL import Image, ImageDraw, ImageFont  # 載入 PIL 相關函式庫

img = cv2.imread("coin.jpg") #輸入資料
h, w, ch = img.shape #圖片高、寬、通道

img = cv2.resize(img, (w//5, h//5), interpolation=cv2.INTER_NEAREST) #縮小圖片

#灰階化
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, gray = cv2.threshold(gray, 90, 255, cv2.THRESH_BINARY)
#侵蝕
gray = cv2.erode(gray, np.ones((2,2)), iterations=2)
#膨脹
gray = cv2.dilate(gray, np.ones((2,2)), iterations=1)
#連通物件
num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(gray, connectivity=8)
print(stats) 
#輸出多少錢
ans = 0
#判斷幾元方法

for it in stats:
  itX = it[0]+it[2] #寬度
  itY = it[1]+it[3] #高度

  if(it[2] >= 60 and it[2] < 75): #1 dallars
    cv2.rectangle(img, (it[0], it[1]), (itX, itY), (0, 0, 255), 2) #BGR 
    ans += 1
  if(it[2] >= 75 and it[2] < 90): #5 dallars
    cv2.rectangle(img, (it[0], it[1]), (itX, itY), (0, 165, 255), 2) #BGR
    ans += 5
  if(it[2] >= 90 and it[2] < 100): #10 dallars
    cv2.rectangle(img, (it[0], it[1]), (itX, itY), (0, 255, 255), 2) #BGR 
    ans += 10
  if(it[2] >= 100 and it[2] < 115): #50 dallars  
    cv2.rectangle(img, (it[0], it[1]), (itX, itY), (0, 128, 0), 2) #BGR
    ans += 50

text = "照片裡有 %s 元" %ans
fontpath = 'NotoSansTC-Regular.ttf'
imgPil = Image.fromarray(img)                # 將 img 轉換成 PIL 影像
draw = ImageDraw.Draw(imgPil)                # 準備開始畫畫
draw.text((50, 0), text, fill=(255, 255, 0), font=ImageFont.truetype(fontpath, 50) )  # 畫入文字
img = np.array(imgPil) 

print("圖上共有 ",ans ,"元") #輸出答案 
cv2.imshow("img", img)
cv2.imwrite('ans.jpg', img)
cv2.imwrite('gray.jpg', gray)
cv2.waitKey(0)

[[     0      0    800    450 270882]
 [   562      0     11     17     91]
 [   561     19      5      2     10]
 [   563     23      3      5     15]
 [   322     61     67     65   2861]
 [   434     76     92     91   6473]
 [   392     94      2      6     12]
 [   237    100     95     92   6834]
 [   389    109      2      2      4]
 [   383    110      2      2      4]
 [   328    129    101    101   7764]
 [   515    128     93     91   6539]
 [   425    171    101     98   6084]
 [   172    172     98     95   7285]
 [   264    208     96     96   7146]
 [   492    221      2      5     10]
 [   466    229     15     11     92]
 [   511    228     95     95   6990]
 [   356    243     96     95   6114]
 [   397    242     18      6     83]
 [   417    244      2      2      4]
 [   181    277     99     99   7697]
 [   444    293     80     83   5117]
 [   277    305     98    100   7605]
 [   378    339     74     76   4284]]
圖上共有  197 元


-1

In [6]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
from PIL import Image, ImageDraw, ImageFont  # 載入 PIL 相關函式庫

def setting(img,h,w):
    img = cv2.resize(img, (w//5, h//5), interpolation=cv2.INTER_LINEAR) #important
    #縮小圖片，記住這邊的 interpolation 選擇很重要，如果不確定建議可以都試試找最棒的

    return img

def coint(img):
    thresh = 127
    maxval = 255
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) #灰階化，方便閱讀
    ret, gray = cv2.threshold(gray, 90, 255, cv2.THRESH_BINARY) #二值化，90 是慢慢設定的

    gray = cv2.erode(gray, np.ones((2,2)), iterations=2) #侵蝕，裡面矩陣與 iterations 細調
    gray = cv2.dilate(gray, np.ones((2,2)), iterations=1) #膨脹，裡面矩陣與 iterations 細調

    ret,gray = cv2.threshold(gray, thresh, maxval, cv2.THRESH_BINARY_INV)#反轉黑白
    
    #連通物件，設八通道這樣才嚴謹

    num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(gray, connectivity=8)
    print(stats)  #檢查所有區塊

    ans = 0 #輸出多少錢

    for it in stats:
        itX = it[0]+it[2] #寬度
        itY = it[1]+it[3] #高度
        cv2.rectangle(img, (it[0], it[1]), (itX, itY), (200, 31, 31), 2)
        #一開始可以使用，這樣她會畫出所有的區塊來讓你判斷有沒有區塊沒畫到或連在一起

        #下面的長度是我自己去慢慢調整出來得
        if(it[2] >= 60 and it[2] < 66 and it[3] > 50): #1 dallars
            cv2.rectangle(img, (it[0], it[1]), (itX, itY), (255, 0, 255), 2) #BGR 
            ans += 1
            print("一元有")
            print(it)
        if(it[2] >= 66 and it[2] < 75): #5 dallars
            cv2.rectangle(img, (it[0], it[1]), (itX, itY), (0, 165, 255), 2) #BGR
            ans += 5
            print("五元有")
            print(it)
        if(it[2] >= 75 and it[2] < 88): #10 dallars
            cv2.rectangle(img, (it[0], it[1]), (itX, itY), (0, 255, 255), 2) #BGR 
            ans += 10
            print("十元有")
            print(it)
        if(it[2] >= 88 and it[2] < 95): #50 dallars  
            cv2.rectangle(img, (it[0], it[1]), (itX, itY), (0, 255, 0), 2) #BGR
            ans += 50
            print("五十元有")
            print(it)
            
    text = "照片裡有 %s 元" %ans
    fontpath = 'NotoSansTC-Regular.ttf'
    imgPil = Image.fromarray(img)                # 將 img 轉換成 PIL 影像
    draw = ImageDraw.Draw(imgPil)                # 準備開始畫畫
    draw.text((50, 0), text, fill=(255, 255, 0), font=ImageFont.truetype(fontpath, 50) )  # 畫入文字
    img = np.array(imgPil)
    cv2.imshow("img", img)
    cv2.imshow('gray.jpg', gray)
    cv2.imwrite('ans.jpg', img)
    cv2.imwrite('gray.jpg', gray)
    cv2.waitKey(0)
    return ans

#cv2.imshow("gray", gray) 
#thresh = 127
#maxval = 255

img = cv2.imread("image1.jpg") #輸入資料
h, w, ch = img.shape #圖片高、寬、通道

img=setting(img,h,w)

ans=coint(img)

print("圖上共有 ",ans ,"元") #輸出答案 


[[     0      0    806    604 464897]
 [   279     79     62     58   2848]
 [   197    113      2      2      4]
 [   148    165     65     61   3047]
 [   592    207     90     88   6108]
 [   505    325      2      2      4]
 [   485    324     62     11    205]
 [   446    331      2      2      4]
 [   516    350      2      2      4]
 [   245    360     87     87   5447]
 [   493    374     73     75   4244]
 [   312    378      3      3      8]
 [   490    574      2      2      4]]
一元有
[ 279   79   62   58 2848]
一元有
[ 148  165   65   61 3047]
五十元有
[ 592  207   90   88 6108]
十元有
[ 245  360   87   87 5447]
五元有
[ 493  374   73   75 4244]
圖上共有  67 元
