In [ ]:
#函式化 
import cv2
import numpy as np
import matplotlib.pyplot as plt

def setting(img,h,w):
    img = cv2.resize(img, (w//5, h//5), interpolation=cv2.INTER_LINEAR) #important
    #縮小圖片，記住這邊的 interpolation 選擇很重要，如果不確定建議可以都試試找最棒的

    return img

def coint(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) #灰階化，方便閱讀
    ret, gray = cv2.threshold(gray, 90, 255, cv2.THRESH_BINARY) #二值化，90 是慢慢設定的

    gray = cv2.erode(gray, np.ones((2,2)), iterations=2) #侵蝕，裡面矩陣與 iterations 細調
    gray = cv2.dilate(gray, np.ones((2,2)), iterations=1) #膨脹，裡面矩陣與 iterations 細調

    #ret,gray = cv2.threshold(gray, thresh, maxval, cv2.THRESH_BINARY_INV)#反轉黑白
    
    #連通物件，設八通道這樣才嚴謹




    num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(gray, connectivity=8)
    print(stats)  #檢查所有區塊

    ans = 0 #輸出多少錢

    for it in stats:
        itX = it[0]+it[2] #寬度
        itY = it[1]+it[3] #高度
        cv2.rectangle(img, (it[0], it[1]), (itX, itY), (200, 31, 31), 2)
        #一開始可以使用，這樣她會畫出所有的區塊來讓你判斷有沒有區塊沒畫到或連在一起

        #下面的長度是我自己去慢慢調整出來得
        if(it[2] >= 60 and it[2] < 75): #1 dallars
            cv2.rectangle(img, (it[0], it[1]), (itX, itY), (0, 0, 255), 2) #BGR 
            ans += 1
        if(it[2] >= 75 and it[2] < 90): #5 dallars
            cv2.rectangle(img, (it[0], it[1]), (itX, itY), (0, 165, 255), 2) #BGR
            ans += 5
        if(it[2] >= 90 and it[2] < 100): #10 dallars
            cv2.rectangle(img, (it[0], it[1]), (itX, itY), (0, 255, 255), 2) #BGR 
            ans += 10
        if(it[2] >= 100 and it[2] < 115): #50 dallars  
            cv2.rectangle(img, (it[0], it[1]), (itX, itY), (0, 128, 0), 2) #BGR
            ans += 50
    cv2.imshow("img", img)
    cv2.imshow('gray.jpg', gray)
    cv2.imwrite('ans.jpg', img)
    cv2.imwrite('gray.jpg', gray)
    cv2.waitKey(0)
    return ans

#cv2.imshow("gray", gray) 
#thresh = 127
#maxval = 255

img = cv2.imread("coin.jpg") #輸入資料
h, w, ch = img.shape #圖片高、寬、通道

img=setting(img,h,w)

ans=coint(img)

print("圖上共有 ",ans ,"元") #輸出答案 


[[     0      0    800    450 270819]
 [   562      0      8     13     71]
 [   560     19      6      9     40]
 [   322     60     67     64   2900]
 [   433     76     93     90   6476]
 [   390     84      2      2      4]
 [   237     99     95     93   6836]
 [   391    102      2      2      4]
 [   383    110      2      2      4]
 [   384    115      3      3      7]
 [   515    127     93     92   6552]
 [   327    129    102    101   7784]
 [   424    168    101    101   6263]
 [   171    172     98     95   7286]
 [   462    196      2      2      4]
 [   264    208     96     95   7144]
 [   482    221      2      2      4]
 [   491    220      3      5     12]
 [   511    227     94     95   6991]
 [   465    231      5      5     18]
 [   356    242     95     95   6029]
 [   401    242     11      6     45]
 [   180    276    100     99   7700]
 [   388    287      2      2      4]
 [   443    293     81     82   5121]
 [   277    305     97     99   7602]
 [   377    

In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

def setting(img,h,w):
    img = cv2.resize(img, (w//5, h//5), interpolation=cv2.INTER_LINEAR) #important
    #縮小圖片，記住這邊的 interpolation 選擇很重要，如果不確定建議可以都試試找最棒的

    return img

def coint(img):
    thresh = 127
    maxval = 255
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) #灰階化，方便閱讀
    ret, gray = cv2.threshold(gray, 90, 255, cv2.THRESH_BINARY) #二值化，90 是慢慢設定的

    gray = cv2.erode(gray, np.ones((2,2)), iterations=2) #侵蝕，裡面矩陣與 iterations 細調
    gray = cv2.dilate(gray, np.ones((2,2)), iterations=1) #膨脹，裡面矩陣與 iterations 細調

    ret,gray = cv2.threshold(gray, thresh, maxval, cv2.THRESH_BINARY_INV)#反轉黑白
    
    #連通物件，設八通道這樣才嚴謹

    num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(gray, connectivity=8)
    print(stats)  #檢查所有區塊

    ans = 0 #輸出多少錢

    for it in stats:
        itX = it[0]+it[2] #寬度
        itY = it[1]+it[3] #高度
        cv2.rectangle(img, (it[0], it[1]), (itX, itY), (200, 31, 31), 2)
        #一開始可以使用，這樣她會畫出所有的區塊來讓你判斷有沒有區塊沒畫到或連在一起

        #下面的長度是我自己去慢慢調整出來得
        if(it[2] >= 60 and it[2] < 66 and it[3] > 50): #1 dallars
            cv2.rectangle(img, (it[0], it[1]), (itX, itY), (255, 0, 255), 2) #BGR 
            ans += 1
            print("一元有")
            print(it)
        if(it[2] >= 66 and it[2] < 75): #5 dallars
            cv2.rectangle(img, (it[0], it[1]), (itX, itY), (0, 165, 255), 2) #BGR
            ans += 5
            print("五元有")
            print(it)
        if(it[2] >= 75 and it[2] < 88): #10 dallars
            cv2.rectangle(img, (it[0], it[1]), (itX, itY), (0, 255, 255), 2) #BGR 
            ans += 10
            print("十元有")
            print(it)
        if(it[2] >= 88 and it[2] < 95): #50 dallars  
            cv2.rectangle(img, (it[0], it[1]), (itX, itY), (0, 255, 0), 2) #BGR
            ans += 50
            print("五十元有")
            print(it)
    cv2.imshow("img", img)
    cv2.imshow('gray.jpg', gray)
    cv2.imwrite('ans.jpg', img)
    cv2.imwrite('gray.jpg', gray)
    cv2.waitKey(0)
    return ans

#cv2.imshow("gray", gray) 
#thresh = 127
#maxval = 255

img = cv2.imread("image1.jpg") #輸入資料
h, w, ch = img.shape #圖片高、寬、通道

img=setting(img,h,w)

ans=coint(img)

print("圖上共有 ",ans ,"元") #輸出答案 


[[     0      0    806    604 464897]
 [   279     79     62     58   2848]
 [   197    113      2      2      4]
 [   148    165     65     61   3047]
 [   592    207     90     88   6108]
 [   505    325      2      2      4]
 [   485    324     62     11    205]
 [   446    331      2      2      4]
 [   516    350      2      2      4]
 [   245    360     87     87   5447]
 [   493    374     73     75   4244]
 [   312    378      3      3      8]
 [   490    574      2      2      4]]
一元有
[ 279   79   62   58 2848]
一元有
[ 148  165   65   61 3047]
五十元有
[ 592  207   90   88 6108]
十元有
[ 245  360   87   87 5447]
五元有
[ 493  374   73   75 4244]
圖上共有  67 元
